services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    #------------Listeners
    CoreBundle\EventListener\ReferenceTranslatorListener:
        tags:
            - { name: doctrine.event_listener, event: postLoad, lazy: true }

    CoreBundle\EventListener\EntitySetAgencyListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist, lazy: true }

    #------------Mangers
    CoreBundle\Manager\AbstractManager: ~

    #------------Controllers