services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    #------------Services
    CoreBundle\Service\FileUploader:
        arguments:
            $targetDirectory: '%upload_directory%'

    #------------Listeners
    CoreBundle\EventListener\ReferenceTranslatorListener:
        tags:
            - { name: doctrine.event_listener, event: postLoad, lazy: true }

    CoreBundle\EventListener\EntitySetAgencyListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist, lazy: true }

    CoreBundle\EventListener\EntityPermissionListener:
        tags:
            - { name: doctrine.event_listener, event: postLoad, lazy: true }

    CoreBundle\EventListener\FileUploadListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    #------------Mangers
    CoreBundle\Manager\AbstractManager: ~

    #------------Controllers