# car
car_list:
    path: /
    defaults: { _controller: CarBundle:Car:list }
    methods: [GET]

car_car_edit:
    path: /edit/{id}
    defaults: { _controller: CarBundle:Car:edit, id: default }
    methods: [GET,POST]
    requirements:
        id: '\d+'