<?php

namespace AppBundle\Repository;

/**
 * AbstractPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractPaymentRepository extends \Doctrine\ORM\EntityRepository
{
}
