<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Agency;
use AppBundle\Repository\AbstractRepository;

/**
 * AbstractCustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractCustomerRepository extends AbstractRepository
{

    /**
     * @param Agency $agency
     * @param null $key
     * @return array
     */
    public function findAllByAgency(Agency $agency,$key = null) {
        $qb = $this->filterByAgency($agency,'c');
        if($key){
            $qb->where("(c INSTANCE OF AppBundle\Entity\PhysicalCustomer AND c.id IN (SELECT pc.id FROM AppBundle\Entity\PhysicalCustomer pc WHERE CONCAT(pc.firstName,pc.lastName) LIKE :key OR CONCAT(pc.lastName,pc.firstName) LIKE :key))");
            $qb->orWhere("(c INSTANCE OF AppBundle\Entity\MoralCustomer AND c.id IN (SELECT mc.id FROM AppBundle\Entity\MoralCustomer mc WHERE mc.socialReason LIKE :key OR mc.managerName LIKE :key OR mc.webSite LIKE :key))");
            $qb->leftJoin('c.gender','g')
                ->orWhere("g.label LIKE :key");
            $qb->leftJoin('c.phones','ph')
                ->orWhere("ph.phone LIKE :key");
            $qb->leftJoin('c.emails','e')
                ->orWhere("e.email LIKE :key");
            
            $qb->setParameter('key',"%" . $key . "%");
        }
        return $qb->getQuery()->getResult();
    }


}
