<?php

namespace AppBundle\Repository;

/**
 * CustomerDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
