<?php

namespace  AppBundle\Repository;

/**
 * MaintenanceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaintenanceTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
