<?php

namespace AppBundle\Repository;

/**
 * MoralCustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoralCustomerRepository extends \Doctrine\ORM\EntityRepository
{
}
