<?php

namespace AppBundle\Repository;

/**
 * OutgoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OutgoRepository extends \Doctrine\ORM\EntityRepository
{
}
