<?php

namespace AppBundle\Repository;

/**
 * PaymentDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
