<?php

namespace AppBundle\Repository;

/**
 * SlCarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlCarRepository extends \Doctrine\ORM\EntityRepository
{
}
