app:
    resource: '@AppBundle/Controller/'
    type: annotation

customer:
    resource: '@CustomerBundle/Controller/'
    type: annotation

car:
    resource: '@CarBundle/Controller/'
    type: annotation

ben_doctors:
    resource: "@CarBundle/Resources/config/routing.yml"
    prefix:   /


ben_user:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /