app:
    resource: '@AppBundle/Controller/'
    type: annotation

customer:
    resource: '@AppBundle/Controller/'
    type: annotation

car:
    resource: '@AppBundle/Controller/'
    type: annotation

ben_user:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
