<?php

namespace CoreBundle\Repository;

/**
 * AbstractDocumentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractDocumentTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
