<?php

namespace CoreBundle\Repository;

/**
 * AbstractDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
