services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    #------------Mangers
    CustomerBundle\Manager\AbstractCustomerManager: ~
    CustomerBundle\Manager\PhysicalCustomerManager: ~

    #------------Controllers
    CustomerBundle\Controller\CustomerController: ~
