<?php

namespace CarBundle\Repository;

/**
 * AbstractCarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractCarRepository extends \Doctrine\ORM\EntityRepository
{
}
