<?php

namespace CarBundle\Repository;

/**
 * CarDocumentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarDocumentTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
