<?php

namespace CarBundle\Repository;

/**
 * CarMaintenanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarMaintenanceRepository extends \Doctrine\ORM\EntityRepository
{
}
