<?php

namespace CarBundle\Repository;

/**
 * CarOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
