<?php

namespace CarBundle\Repository;

use CoreBundle\Repository\AbstractRepository;
use CoreBundle\Entity\Agency;
/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends AbstractRepository
{
    /**
     * @param Agency $agency
     * @param null $key
     * @param bool $withResult
     * @return array|\Doctrine\ORM\QueryBuilder
     */
    public function findAllByAgency(Agency $agency, $key = null, $withResult = true){
        $qb = $this->filterByAgency($agency,'c');
        if($key){
            $qb->leftJoin('c.model','m')
                ->leftJoin('m.brand','b')
                ->where('b.label LIKE :key')
                ->leftJoin('c.options','o')
                ->orWhere('o.label LIKE :key')
                ->leftJoin('c.fuelType','f')
                ->orWhere('f.label LIKE :key')
                ->leftJoin('c.gearBox','g')
                ->orWhere('g.label LIKE :key')
                ->orWhere('c.carNumber LIKE :key')
                ->orWhere('c.carNumberWW LIKE :key')
            ;

            $qb->setParameter('key',"%" . $key . "%");
        }
        return $withResult ? $qb->getQuery()->getResult() : $qb;
    }

}
