<?php

namespace CustomerBundle\Repository;

/**
 * CustomerDocumentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerDocumentTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
