<?php

namespace CustomerBundle\Repository;

/**
 * PhysicalCustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhysicalCustomerRepository extends \Doctrine\ORM\EntityRepository
{
}
