<?php

namespace CustomerBundle\Repository;
use CoreBundle\Entity\Agency;

/**
 * PhysicalCustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhysicalCustomerRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param Agency $agency
     * @return array
     */
    public function findAllByAgency(Agency $agency) {
        return $this->filterByAgency($agency)->getQuery()->getResult();
    }

    /**
     * @param Agency $agency
     * @return \Doctrine\ORM\QueryBuilder
     */
    private function filterByAgency(Agency $agency)
    {
        $qb = $this->createQueryBuilder('pc')
            ->join('pc.agency', 'ag', 'WITH', 'ag.id = :agencyId')
            ->setParameter('agencyId', $agency->getId());

        return $qb;
    }
}
