services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    #------------Mangers
    CarBundle\Manager\CarManager: ~
    CarBundle\Manager\CarMaintenanceManager: ~

    #------------Controllers
    CarBundle\Controller\CarMaintenanceController: ~
    CarBundle\Controller\CarController: ~

    #------------Form Type
    CarBundle\Form\CarMaintenanceType: ~
