services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    #------------Mangers
    CarBundle\Manager\CarMaintenanceManager: ~

    #------------Controllers
    CarBundle\Controller\CarMaintenanceController: ~
